{% set goname = "k8s.io/federation" %}
{% set version = "1.9.0" %}
{% set version_suffix = "alpha.3" %}


{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", os.sep) %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}{{ version_suffix[0] }}{{ version_suffix.split('.')[-1] }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}-{{version_suffix}}.tar.gz
    sha256: 9cbc8fb14318a5ebd9bf4c4a7f8a1a5e7508445c9488e59c58482c3c2607f6bb

build:
  skip: True  # [not linux]
  number: 1000

requirements:
  build:
    - {{ compiler('go') }} 1.8
    - rsync
    - make

test:
  commands:
    - fcp --help
    - federation-apiserver --help
    - federation-controller-manager --help
    - kubefed help

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: {{pkg_src}}/LICENSE
  summary: Production-Grade Container Orchestration / Federation
  doc_url: https://docs.kubernetes.io/docs/home/
  dev_url: https://github.com/kubernetes/federation

extra:
  recipe-maintainers:
    - sodre
