travis:
  secure:
    BINSTAR_TOKEN: EB2HIaI2BtxIQY882xZeS4R00Waq6tsvih8TMjknYB9c8PYkuOaoVQY47OemFrnNvoec5U75hUYVCeGXRU9ms0YgltORFCStNA1QDDfuLWNSf7GNS6f9jHU/cc1Kdm/r2xYom0yqh5ytms1O75bnAYE+nFdIwFuc0b3ZSLIRSLCVSkMtq1QN2qugSwFIL2SZrxWyCZ8mhbhPy5NnCD2yKxn8GIrsuuSOzjnPML+hh7h6TzFm/sZh1ysX9WmJlNnQvjiSdzV7Rdoy6Mxb4HVFuNztu2Ac8KmnhTbFujhPwGmXQlFL30RZcsISIH/r8nutZXhlRYMFLi235JnwGlDoBJu8r8YCSo4tQgvqeeLiAUzPd2ow6UU1foelNO6Y4P+ZXTHXD3ghzUWBJlNGj8kq80gE8fqT2LQ4iqAMlukW8iq+FQTxJ7tJlYG2J3fJNpp/gFYUVSPhyRn5BIflAHBGghbpSSnOCR+otLWUdUuUTWP6hn0o9JNVa3uON27PZ0pj8yUbUQ4wDLhzcFntysJ1lMGe4z/VSpArSzpxzPzp5kpqHmXhQ1VExUtz2hXsd08Avl2i059wp2G/bu/1PcR9v47diBHurs9c558r/CulEUGJyv23AGU9mWseaeLYeHhuGg0yyjx8gbui/Ntbd9UK3nJJwB1tmqKJfvyXXpvc5aw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
