appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Nfq53f3ZQEuEo89ORelR3vgkWp8m5v8ydeEKuGWXnaqdWXOXhPvLjXbVdzud9RNcsIk3gCjUCwALi+QP2xsZY/5bgBrq8OpxRXT33WUmg0aexWhajFRcFx5xmdnmYho9IXuyprdnuCHuYZereYnMuv2TxV9LKJhprlOrCkWn78daAgSNc/8pr2vTTnKzmLTEGqzkJfmvL+tT9FaI6CHK9PcPz5TUE/9CJ7zjuGtxqMEtQYjN4lBsSw+Ztzs7mUBaGbhTsnHvmwdgGULFjfDYKuwHbdzw/3acPwYWdFLwsOJGROP2hVvnd4o/IkOP+mcFpVbKqLh1RBifiSEuZwPm0282oVMy7QTlt6TaztXK7cm+Tj79QOhPzsMtI/p/y80XfLjrazXEiEC9LR7PRPY078XQbmmUkvbpCZIx8QCxiGb0n9fJQomzVJtgsLenk45h3wvocRPujxB9H5sB61IAWJR2gnvyT+QPzS1vhbiRMX1k13gaMuZ23NU262oEeiIffmaIfbQD4OoXk8RFz57ORlr2LofVhMCR6452JRAUgQlXUh+nAWCRb0yXKOSWdNfz+0oaBJ71G9fkdZy6Y62IEQFd+BKZ8yeI4BtEq1500ahXnSEnJoJ28r4CCfzBmU8L0f1g6u1PnnwJ+MfM3z5kbPOV9J5oLd75jnU0Jyb2IwY=}
